ALTER TABLE skn_channels CHANGE allyowner allyOwner_id INTEGER;
ALTER TABLE skn_channels CHANGE readally readAlly_id INTEGER;
ALTER TABLE skn_channels CHANGE writeally writeAlly_id INTEGER;
UPDATE skn_channels SET allyOwner_id = NULL WHERE allyOwner_id=0;
UPDATE skn_channels SET readAlly_id = NULL WHERE readAlly_id=0;
UPDATE skn_channels SET writeAlly_id = NULL WHERE writeAlly_id=0;
UPDATE skn_channels SET allyOwner_id = NULL WHERE allyOwner_id not in (select id from ally);
alter table skn_channels add index comnet_channel_fk_ally (allyOwner_id), add constraint comnet_channel_fk_ally foreign key (allyOwner_id) references ally (id);
alter table skn_channels add index comnet_channel_fk_ally3 (readAlly_id), add constraint comnet_channel_fk_ally3 foreign key (readAlly_id) references ally (id);
alter table skn_channels add index comnet_channel_fk_ally2 (writeAlly_id), add constraint comnet_channel_fk_ally2 foreign key (writeAlly_id) references ally (id);
ALTER TABLE skn_channels DROP INDEX allyowner;