CREATE TABLE `ally` (
  `id` integer not null auto_increment,
	`allytag` varchar(255) not null,
	`description` longtext not null,
	`destroyedShips` integer not null,
	`founded` datetime not null,
	`hp` longtext not null,
	`items` longtext not null,
	`lostBattles` smallint not null,
	`lostShips` integer not null,
	`name` longtext not null,
  `plainname` varchar(255) not null,
	`pname` varchar(255) not null,
	`showGtuBieter` tinyint not null,
	`showastis` boolean not null,
  `showlrs` tinyint not null,
	`tick` integer not null,
	`version` integer not null,
	`wonBattles` smallint not null,
	`president` integer not null,
	primary key (`id`),
	unique (president)
) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
