CREATE TABLE `ally` (
  `id` int(11) NOT NULL auto_increment,
  `name` LONGTEXT NOT NULL,
  `plainname` varchar(255) NOT NULL,
  `founded` datetime NOT NULL,
  `tick` int(11) NOT NULL,
  `president` integer NOT NULL,
  `description` LONGTEXT NOT NULL,
  `hp` LONGTEXT NOT NULL,
  `allytag` varchar(255) NOT NULL,
  `showastis` BOOLEAN NOT NULL,
  `showGtuBieter` tinyint NOT NULL,
  `showlrs` tinyint NOT NULL,
  `pname` varchar(255) NOT NULL,
  `items` LONGTEXT NOT NULL,
  `lostBattles` smallint NOT NULL,
  `wonBattles` smallint NOT NULL,
  `destroyedShips` INTEGER NOT NULL,
  `lostShips` INTEGER NOT NULL,
  `version` INTEGER NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
