INSERT INTO `ammo` (`id`, `name`, `type`, `damage`, `shielddamage`, `subdamage`, `trefferws`, `smalltrefferws`, `torptrefferws`, `subws`, `shotspershot`, `areadamage`, `destroyable`, `flags`) VALUES (1, 'Flakmagazine', 'flak', 6, 3, 0, 50, 65, 4, 0, 5, 1, 0.00, 0);
INSERT INTO `ammo` (`id`, `name`, `type`, `damage`, `shielddamage`, `subdamage`, `trefferws`, `smalltrefferws`, `torptrefferws`, `subws`, `shotspershot`, `areadamage`, `destroyable`, `flags`) VALUES (2, 'GTM MX-64 Rockeye', 'rak', 45, 25, 0, 80, 50, 0, 0, 1, 0, 0.00, 0);
INSERT INTO `ammo` (`id`, `name`, `type`, `damage`, `shielddamage`, `subdamage`, `trefferws`, `smalltrefferws`, `torptrefferws`, `subws`, `shotspershot`, `areadamage`, `destroyable`, `flags`) VALUES (3, 'GTM-13 Helios', 'torp', 6800, 6800, 0, 45, 14, 0, 0, 1, 0, 1.00, 0);
INSERT INTO `ammo` (`id`, `name`, `type`, `damage`, `shielddamage`, `subdamage`, `trefferws`, `smalltrefferws`, `torptrefferws`, `subws`, `shotspershot`, `areadamage`, `destroyable`, `flags`) VALUES (5, 'Schwere Flakmagazine', 'heavyflak', 10, 5, 0, 50, 65, 8, 0, 5, 2, 0.00, 0);
INSERT INTO `ammo` (`id`, `name`, `type`, `damage`, `shielddamage`, `subdamage`, `trefferws`, `smalltrefferws`, `torptrefferws`, `subws`, `shotspershot`, `areadamage`, `destroyable`, `flags`) VALUES (7, 'GTM-4 Hornet', 'rak', 50, 25, 0, 95, 58, 0, 0, 4, 0, 0.00, 0);
INSERT INTO `ammo` (`id`, `name`, `type`, `damage`, `shielddamage`, `subdamage`, `trefferws`, `smalltrefferws`, `torptrefferws`, `subws`, `shotspershot`, `areadamage`, `destroyable`, `flags`) VALUES (12, 'GTM-10 Piranha', 'rak', 150, 160, 0, 95, 100, 0, 0, 1, 2, 0.00, 1);
INSERT INTO `ammo` (`id`, `name`, `type`, `damage`, `shielddamage`, `subdamage`, `trefferws`, `smalltrefferws`, `torptrefferws`, `subws`, `shotspershot`, `areadamage`, `destroyable`, `flags`) VALUES (14, 'GTM-11 Infyrno', 'rak', 150, 122, 0, 95, 60, 0, 0, 2, 3, 0.00, 0);
INSERT INTO `ammo` (`id`, `name`, `type`, `damage`, `shielddamage`, `subdamage`, `trefferws`, `smalltrefferws`, `torptrefferws`, `subws`, `shotspershot`, `areadamage`, `destroyable`, `flags`) VALUES (20, 'NTF EM-Plasma', 'hhplasma', 500, 24000, 0, 80, 20, 0, 0, 1, 0, 0.00, 0);
INSERT INTO `ammo` (`id`, `name`, `type`, `damage`, `shielddamage`, `subdamage`, `trefferws`, `smalltrefferws`, `torptrefferws`, `subws`, `shotspershot`, `areadamage`, `destroyable`, `flags`) VALUES (33, 'Bergbausprengstoff', 'bum', 6800, 6800, 0, 0, 0, 0, 0, 1, 0, 1.00, 0);
