CREATE TABLE `bases` (
  `id` integer not null auto_increment,
	`active` text not null,
	`arbeiter` int(11) unsigned not null default '0',
	`autogtuacts` text not null,
	`bebauung` text not null,
	`bewohner` int(11) unsigned not null default '0',
	`cargo` text not null,
	`core` integer not null default '0',
	`coreactive` tinyint(3) unsigned not null default '0',
	`e` int(11) unsigned not null default '0',
	`height` int(5) not null default '8',
	`isfeeding` tinyint(1) not null default '1',
	`isloading` tinyint(1) not null default '1',
	`maxcargo` integer not null default '0',
	`maxe` smallint(5) unsigned not null default '1000',
	`maxtiles` smallint(6) not null default '0',
	`name` varchar(50) not null default 'Leerer Asteroid',
	`size` tinyint(3) unsigned not null default '0',
	`spawnableress` text,
	`spawnressavailable` text,
	`system` tinyint(4) not null default '1',
	`terrain` text not null,
	`version` integer not null default '0',
	`width` int(5) not null default '5',
	`x` integer not null default '1',
	`y` integer not null default '1',
	academy_id int,
	forschungszentrum_id int,
	`klasse` int(5) not null default '1',
	`owner` integer not null default '0',
	werft_id int,
	`unitcargo` varchar (120),
  primary key (`id`),
  key `owner` (`owner`,`id`),
  key `coords` (`x`,`y`,`system`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;