CREATE TABLE `battles` (
  `id` integer not null auto_increment,
	`ally1` integer not null,
	`ally2` integer not null,
	`blockcount` integer not null,
	`com1BETAK` boolean not null,
	`com2BETAK` boolean not null,
	`flags` integer not null,
	`lastaction` bigint not null,
	`lastturn` bigint not null,
	`onend` longtext,
	`ready1` boolean not null,
	`ready2` boolean not null,
	`system` integer not null,
	`takeCommand1` integer not null,
	`takeCommand2` integer not null,
	`version` integer not null,
	`visibility` longtext,
	`x` integer not null,
  `y` integer not null,
  `commander1` integer not null,
  `commander2` integer not null,
  primary key (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;