CREATE TABLE `buildings` (
  `id` integer not null auto_increment,
	`arbeiter` integer not null,
	`bewohner` integer not null,
	`buildcosts` varchar(255) not null,
	`category` integer not null,
	`chanceress` varchar(255),
	`consumes` varchar(255) not null,
	`deakable` boolean not null,
	`eprodu` integer not null,
	`ever` integer not null,
	`eps` integer not null,
	`module` varchar(255) not null,
	`name` varchar(255) not null,
	`perowner` integer not null,
	`perplanet` integer not null,
	`picture` varchar(255) not null,
  `produces` varchar(255) not null,
	`race` integer not null,
	`shutdown` boolean not null,
	`techreq` integer not null,
	`terrain` longtext,
	`ucomplex` boolean not null,
  primary key (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
