CREATE TABLE `offiziere` (
  `id` integer not null auto_increment,
	`com` integer not null,
	`comu` integer not null,
	`ing` integer not null,
	`ingu` integer not null,
	`name` varchar(255) not null,
	`nav` integer not null,
	`navu` integer not null,
	`rang` integer not null,
	`sec` integer not null,
	`secu` integer not null,
	`spec` integer not null,
	training boolean not null,
	`waf` integer not null,
	`wafu` integer not null,
	`userid` integer not null,
	stationiertAufBasis_id integer,
	stationiertAufSchiff_id integer,
	primary key  (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;