CREATE TABLE `quests_quick` (
  `id` integer not null auto_increment,
	`awarditems` longtext not null,
	`awardre` bigint not null,
	`dependsOnQuests` varchar(255) not null,
	`description` longtext not null,
	`enabled` integer not null,
	`finishtext` longtext not null,
	`head` varchar(255) not null,
	`loottable` longtext,
	`moreThanOnce` integer not null,
	`notyettext` longtext not null,
	`qid` varchar(255) not null,
  `qname` varchar(255) not null,
	`reqitems` longtext not null,
	`reqre` bigint not null,
  `shortdesc` longtext not null,
  `source` varchar(255) not null,
  `sourcetype` varchar(255) not null,
	`startitems` longtext not null,
  `target` varchar(255) not null,
  `targettype` varchar(255) not null,
  primary key  (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;