CREATE TABLE `quests_quick` (
  `id` int(10) unsigned NOT NULL auto_increment,
  `qid` varchar(30) NOT NULL default '',
  `enabled` int(10) unsigned NOT NULL default '0',
  `qname` varchar(60) NOT NULL default '',
  `dependsOnQuests` varchar(100) NOT NULL default '',
  `moreThanOnce` tinyint(3) unsigned NOT NULL default '0',
  `head` varchar(20) NOT NULL default 'ars.gif',
  `desc` text NOT NULL,
  `shortdesc` text NOT NULL,
  `finishtext` text NOT NULL,
  `notyettext` text NOT NULL,
  `source` int(10) unsigned NOT NULL default '0',
  `sourcetype` varchar(20) NOT NULL default 'gtuposten',
  `target` int(10) unsigned NOT NULL default '0',
  `targettype` varchar(20) NOT NULL default 'gtuposten',
  `startitems` text NOT NULL,
  `reqitems` text NOT NULL,
  `reqre` int(10) unsigned NOT NULL default '0',
  `awarditems` text NOT NULL,
  `awardre` text NOT NULL,
  `loottable` text,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
