INSERT INTO `schiffstyp_modifikation_flags` (`SchiffstypModifikation_id`, `flags`) VALUES (408,3);
INSERT INTO `schiffstyp_modifikation_flags` (`SchiffstypModifikation_id`, `flags`) VALUES (338,4);
INSERT INTO `schiffstyp_modifikation_flags` (`SchiffstypModifikation_id`, `flags`) VALUES (339,4);
INSERT INTO `schiffstyp_modifikation_flags` (`SchiffstypModifikation_id`, `flags`) VALUES (341,4);
INSERT INTO `schiffstyp_modifikation_flags` (`SchiffstypModifikation_id`, `flags`) VALUES (343,4);
INSERT INTO `schiffstyp_modifikation_flags` (`SchiffstypModifikation_id`, `flags`) VALUES (395,4);
INSERT INTO `schiffstyp_modifikation_flags` (`SchiffstypModifikation_id`, `flags`) VALUES (442,4);
INSERT INTO `schiffstyp_modifikation_flags` (`SchiffstypModifikation_id`, `flags`) VALUES (311,6);
INSERT INTO `schiffstyp_modifikation_flags` (`SchiffstypModifikation_id`, `flags`) VALUES (409,6);
INSERT INTO `schiffstyp_modifikation_flags` (`SchiffstypModifikation_id`, `flags`) VALUES (301,9);
INSERT INTO `schiffstyp_modifikation_flags` (`SchiffstypModifikation_id`, `flags`) VALUES (341,9);
INSERT INTO `schiffstyp_modifikation_flags` (`SchiffstypModifikation_id`, `flags`) VALUES (329,10);
INSERT INTO `schiffstyp_modifikation_flags` (`SchiffstypModifikation_id`, `flags`) VALUES (381,11);
INSERT INTO `schiffstyp_modifikation_flags` (`SchiffstypModifikation_id`, `flags`) VALUES (410,11);
INSERT INTO `schiffstyp_modifikation_flags` (`SchiffstypModifikation_id`, `flags`) VALUES (395,12);
INSERT INTO `schiffstyp_modifikation_flags` (`SchiffstypModifikation_id`, `flags`) VALUES (339,13);
INSERT INTO `schiffstyp_modifikation_flags` (`SchiffstypModifikation_id`, `flags`) VALUES (344,14);
INSERT INTO `schiffstyp_modifikation_flags` (`SchiffstypModifikation_id`, `flags`) VALUES (374,14);
INSERT INTO `schiffstyp_modifikation_flags` (`SchiffstypModifikation_id`, `flags`) VALUES (395,14);
INSERT INTO `schiffstyp_modifikation_flags` (`SchiffstypModifikation_id`, `flags`) VALUES (344,15);
INSERT INTO `schiffstyp_modifikation_flags` (`SchiffstypModifikation_id`, `flags`) VALUES (374,15);
INSERT INTO `schiffstyp_modifikation_flags` (`SchiffstypModifikation_id`, `flags`) VALUES (395,15);
INSERT INTO schiffstyp_modifikation_flags (SchiffstypModifikation_id, flags) VALUES (9532, 9);
INSERT INTO schiffstyp_modifikation_flags (SchiffstypModifikation_id, flags) VALUES (9532, 12);
INSERT INTO schiffstyp_modifikation_flags (SchiffstypModifikation_id, flags) VALUES (9533, 9);
INSERT INTO schiffstyp_modifikation_flags (SchiffstypModifikation_id, flags) VALUES (9533, 12);
INSERT INTO schiffstyp_modifikation_flags (SchiffstypModifikation_id, flags) VALUES (9533, 11);
INSERT INTO schiffstyp_modifikation_flags (SchiffstypModifikation_id, flags) VALUES (9534, 9);
INSERT INTO schiffstyp_modifikation_flags (SchiffstypModifikation_id, flags) VALUES (9534, 12);
INSERT INTO schiffstyp_modifikation_flags (SchiffstypModifikation_id, flags) VALUES (9534, 11);
INSERT INTO schiffstyp_modifikation_flags (SchiffstypModifikation_id, flags) VALUES (9534, 6);
INSERT INTO schiffstyp_modifikation_flags (SchiffstypModifikation_id, flags) VALUES (9535, 9);
INSERT INTO schiffstyp_modifikation_flags (SchiffstypModifikation_id, flags) VALUES (9535, 12);
INSERT INTO schiffstyp_modifikation_flags (SchiffstypModifikation_id, flags) VALUES (9535, 11);
INSERT INTO schiffstyp_modifikation_flags (SchiffstypModifikation_id, flags) VALUES (9535, 6);
INSERT INTO schiffstyp_modifikation_flags (SchiffstypModifikation_id, flags) VALUES (9535, 4);
INSERT INTO schiffstyp_modifikation_flags (SchiffstypModifikation_id, flags) VALUES (9535, 10);
INSERT INTO schiffstyp_modifikation_flags (SchiffstypModifikation_id, flags) VALUES (9539, 3);
INSERT INTO schiffstyp_modifikation_flags (SchiffstypModifikation_id, flags) VALUES (9539, 11);
INSERT INTO schiffstyp_modifikation_flags (SchiffstypModifikation_id, flags) VALUES (9541, 12);