INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (1,4,20,0,0,'Prometheus',320);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (2,4,20,0,0,'Kayser',321);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (3,4,20,0,0,'Shivan_Heavy_Laser',327);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (4,4,20,0,0,'Circe',328);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (5,2,10,0,0,'standard_flak',335);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (6,2,40,0,0,'standard_flak',336);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (7,0,30,0,0,'BGreen',343);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (8,1,10,0,0,'BGreen',348);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (9,4,60,0,0,'heavy_flak_ld',349);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (10,1,15,0,0,'BVas',355);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (11,2,60,0,0,'Terran_Huge_Turret',356);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (12,1,20,0,0,'Terran_Huge_Turret',358);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (13,1,18,0,0,'BGreen',362);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (14,-4,0,0,0,'heavy_flak',363);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (15,1,35,0,0,'BVas',369);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (16,-4,0,0,0,'AAAf',370);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (17,-4,0,0,0,'TerSlash',374);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (18,-2,0,0,0,'BVas',375);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (19,-5,0,0,0,'standard_flak',376);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (20,2,10,0,0,'TerSlash',382);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (21,10,200,0,0,'standard_flak_ld',387);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (22,5,50,0,0,'lrraketen',388);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (23,4,60,0,0,'heavy_pulse_gun',389);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (24,4,80,0,0,'ntfraketen',390);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (25,1,15,0,0,'BVas',396);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (26,2,60,0,0,'Terran_Huge_Turret',397);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (27,1,15,0,0,'BVas',400);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (28,-4,0,0,0,'Subach_HL-7',403);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (29,10,200,0,0,'standard_flak',404);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (30,10,100,0,0,'lrraketen',405);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (31,1,10,0,0,'TerSlash',411);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (32,2,10,0,0,'TerSlash',415);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (33,0,30,0,0,'TerSlash',343);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (34,0,80,0,0,'Terran_Huge_Turret',343);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (35,1,10,0,0,'TerSlash',348);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (36,1,10,0,0,'Terran_Turret',348);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (37,4,60,0,0,'LRAAAF',349);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (38,-3,0,0,0,'AAAf',349);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (39,-5,0,0,0,'standard_flak',356);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (40,6,90,0,0,'standard_flak_ld',356);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (41,4,60,0,0,'LRAAAF',356);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (42,2,20,0,0,'doubleraketen',356);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (43,-2,0,0,0,'AAAf',356);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (44,0,50,0,0,'standard_flak',356);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (45,1,10,0,0,'doubleraketen',358);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (46,1,15,0,0,'TerSlash',362);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (47,2,30,0,0,'Terran_Huge_Turret',362);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (48,-6,0,0,0,'standard_flak',363);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (49,-6,0,0,0,'AAAf',363);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (50,4,60,0,0,'heavy_flak_ld',363);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (51,6,90,0,0,'standard_flak_ld',363);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (52,6,90,0,0,'LRAAAF',363);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (53,4,60,0,0,'SVas',369);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (54,4,80,0,0,'doubleraketen',370);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (55,-11,0,0,0,'standard_flak',370);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (56,6,90,0,0,'LRAAAF',370);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (57,10,200,0,0,'standard_flak_ld',370);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (58,0,50,0,0,'raketen',370);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (59,2,12,0,0,'heavy_pulse_gun',374);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (60,-4,0,0,0,'Terran_Huge_Turret',374);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (61,4,40,0,0,'light_pulse_gun',374);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (62,-6,0,0,0,'Terran_Turret',374);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (63,15,150,0,0,'mikro_pulse_gun',374);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (64,-6,0,0,0,'standard_flak',374);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (65,6,36,0,0,'heavy_flak',374);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (66,-2,0,0,0,'Terran_Huge_Turret',375);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (67,-2,0,0,0,'AAAf',376);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (68,3,24,0,0,'AAAf',382);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (69,8,120,0,0,'light_pulse_gun',389);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (70,2,20,0,0,'doubleraketen',397);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (71,1,40,0,0,'AAAf',397);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (72,0,50,0,0,'standard_flak',397);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (73,4,24,0,0,'Kayser',403);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (74,1,1,0,0,'kamikaze_cruiser',403);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (75,2,16,0,0,'raketen',403);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (76,1,8,0,0,'AAAf',403);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (77,-2,0,0,0,'Terran_Turret',403);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (78,10,200,0,0,'standard_flak_ld',404);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (79,1,30,0,0,'AAAf',411);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (80,2,20,0,0,'raketen',411);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (81,2,50,0,0,'standard_flak',411);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (82,-6,0,0,0,'Terran_Turret',411);
INSERT INTO `schiffswaffenkonfiguration` (`id`, `anzahl`, `hitze`, `maxUeberhitzung`, `version`, `waffe_id`, `schiffstyp_modifikation_id`) VALUES (83,3,24,0,0,'AAAf',415);
INSERT INTO schiffswaffenkonfiguration (id, anzahl, hitze, maxUeberhitzung, version, waffe_id, schiffstyp_modifikation_id) VALUES (null, 1, 1, 0, 0, 'set_hol_shrine_of_sacrifice', 9535);
INSERT INTO schiffswaffenkonfiguration (id, anzahl, hitze, maxUeberhitzung, version, waffe_id, schiffstyp_modifikation_id) VALUES (null, 0, 120, 0, 0, 'AAAf', 9536);
INSERT INTO schiffswaffenkonfiguration (id, anzahl, hitze, maxUeberhitzung, version, waffe_id, schiffstyp_modifikation_id) VALUES (null, 0, 80, 0, 0, 'heavy_flak', 9536);
INSERT INTO schiffswaffenkonfiguration (id, anzahl, hitze, maxUeberhitzung, version, waffe_id, schiffstyp_modifikation_id) VALUES (null, 0, 40, 0, 0, 'BGreen', 9536);
INSERT INTO schiffswaffenkonfiguration (id, anzahl, hitze, maxUeberhitzung, version, waffe_id, schiffstyp_modifikation_id) VALUES (null, 0, 120, 0, 0, 'standard_flak', 9536);
INSERT INTO schiffswaffenkonfiguration (id, anzahl, hitze, maxUeberhitzung, version, waffe_id, schiffstyp_modifikation_id) VALUES (null, 8, 80, 0, 0, 'BVas', 9537);
INSERT INTO schiffswaffenkonfiguration (id, anzahl, hitze, maxUeberhitzung, version, waffe_id, schiffstyp_modifikation_id) VALUES (null, 10, 100, 0, 0, 'heavy_flak', 9537);
INSERT INTO schiffswaffenkonfiguration (id, anzahl, hitze, maxUeberhitzung, version, waffe_id, schiffstyp_modifikation_id) VALUES (null, 6, 60, 0, 0, 'AAAf', 9537);
INSERT INTO schiffswaffenkonfiguration (id, anzahl, hitze, maxUeberhitzung, version, waffe_id, schiffstyp_modifikation_id) VALUES (null, 1, 3, 0, 0, 'set_ewige_verdammnis', 9537);
