create index coords on ships (system, x, y);
create index docked on ships (docked);
create index status on ships (status);
create index owner on ships (owner, id);
alter table ships add index ships_fk_ship_script_data (scriptData_id), add constraint ships_fk_ship_script_data foreign key (scriptData_id) references ship_script_data (shipid);
alter table ships add index ships_fk_ship_fleets (fleet), add constraint ships_fk_ship_fleets foreign key (fleet) references ship_fleets (id);
alter table ships add index ships_fk_battles (battle), add constraint ships_fk_battles foreign key (battle) references battles(id);
alter table ships add index ships_fk_schiff_einstellungen (einstellungen_id), add constraint ships_fk_schiff_einstellungen foreign key (einstellungen_id) references schiff_einstellungen (id);
alter table ships add index ships_type_fk (type), add constraint ships_type_fk foreign key (type) references ship_types (id);
alter table ships add index ships_fk_users (owner), add constraint ships_fk_users foreign key (owner) references users (id);
alter table ships add index ships_fk_ships_modules (modules), add constraint ships_fk_ships_modules foreign key (modules) references ships_modules (id);