CREATE TABLE `ship_types` (
  `id` int(11) NOT NULL auto_increment,
  `nickname` varchar(30) NOT NULL default '',
  `picture` varchar(50) NOT NULL default '',
  `ru` int(11) NOT NULL default '0',
  `rd` int(11) NOT NULL default '0',
  `ra` int(11) NOT NULL default '0',
  `rm` int(11) NOT NULL default '0',
  `eps` int(11) NOT NULL default '0',
  `cost` int(11) NOT NULL default '0',
  `hull` int(11) NOT NULL default '0',
  `panzerung` tinyint(3) unsigned NOT NULL default '0',
  `ablativeArmor` int(11) UNSIGNED NOT NULL default '0',
  `cargo` int(11) NOT NULL default '0',
  `nahrungcargo` int(11) NOT NULL default '0',
  `heat` int(11) NOT NULL default '0',
  `crew` int(11) NOT NULL default '0',
  `weapons` text NOT NULL,
  `maxheat` text NOT NULL,
  `torpedodef` tinyint(3) unsigned NOT NULL default '0',
  `shields` int(11) NOT NULL default '0',
  `size` int(11) NOT NULL default '0',
  `jdocks` int(11) NOT NULL default '0',
  `adocks` int(11) NOT NULL default '0',
  `sensorrange` tinyint(4) NOT NULL default '0',
  `hydro` int(11) NOT NULL default '0',
  `recost` smallint(5) unsigned NOT NULL default '0',
  `descrip` text NOT NULL,
  `deutfactor` tinyint(4) NOT NULL default '0',
  `class` tinyint(3) unsigned NOT NULL default '0',
  `flags` text NOT NULL,
  `groupwrap` tinyint(3) unsigned NOT NULL default '10',
  `werft` int(11) NOT NULL default '0',
  `ow_werft` smallint(5) unsigned NOT NULL default '0',
  `chance4Loot` tinyint(3) unsigned NOT NULL default '0',
  `modules` text NOT NULL,
  `shipcount` tinyint(3) unsigned NOT NULL default '1',
  `hide` tinyint(1) NOT NULL default '0',
  `srs` tinyint NOT NULL default '1',
  `scanCost` INT NOT NULL default '0',
  `pickingCost` INT NOT NULL default '0',
  `minCrew`int NOT NULL default '0',
  `lostInEmpChance` double NOT NULL default '0.75',
  `version` int(10) unsigned not null default '0',
  `maxunitsize` tinyint (4) NOT NULL default '1',
  `unitspace` int (11) NOT NULL default '0',
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
