CREATE TABLE `users` (
  `id` integer not null,
	`accesslevel` integer not null,
	`disabled` tinyint not null,
	`email` varchar(255) not null,
	`flags` longtext not null,
	`imgpath` varchar(255),
	`inakt` integer not null,
	`log_fail` integer not null,
	`name` varchar(255) not null,
	`nickname` varchar(255) not null,
	`passwort` varchar(255) not null,
	`plainname` varchar(255) not null,
	`signup` integer not null,
	`un` varchar(255) not null,
	`version` integer not null,
	`bounty` decimal(19,2) not null,
	`destroyedShips` integer,
	`gtudropzone` integer,
	`history` longtext,
	`knownItems` longtext,
	`konto` decimal(19,2),
	`lostBattles` smallint,
	`lostShips` integer,
	`medals` varchar(255),
	`npcorderloc` varchar(255),
	`npcpunkte` integer,
	personenNamenGenerator varchar(255),
	`race` integer,
	`rang` integer,
	schiffsKlassenNamenGenerator varchar(255),
	schiffsNamenGenerator varchar(255),
	`specializationPoints` integer,
	`vaccount` integer,
	`vacpoints` integer,
	`wait4vac` integer,
	`wonBattles` smallint,
	`ally` integer,
	`allyposten` integer unique,
  primary key (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;