alter table items add column baukosten longtext;
alter table items add column crew integer;
alter table items add column dauer integer;
alter table items add column energiekosten integer;
alter table items add column flagschiff boolean;
alter table items add column werftSlots integer;
alter table items add column schiffsbauplan_rasse_id integer;
alter table items add column schiffsbauplan_schiffstyp_id integer;
create table schiffsbauplan_forschungen (items_id integer not null, benoetigteForschungen_id integer not null, primary key (items_id, benoetigteForschungen_id)) ENGINE=InnoDB;
alter table items add index schiffsbauplan_fk_rasse (schiffsbauplan_rasse_id), add constraint schiffsbauplan_fk_rasse foreign key (schiffsbauplan_rasse_id) references rasse (id);
alter table items add index schiffsbauplan_fk_schiffstyp (schiffsbauplan_schiffstyp_id), add constraint schiffsbauplan_fk_schiffstyp foreign key (schiffsbauplan_schiffstyp_id) references ship_types (id);
alter table schiffsbauplan_forschungen add index schiffsbauplan_forschungen_fk_schiffsbauplan (benoetigteForschungen_id), add constraint schiffsbauplan_forschungen_fk_schiffsbauplan foreign key (benoetigteForschungen_id) references forschungen (id);
alter table schiffsbauplan_forschungen add index schiffsbauplan_fk_forschungen (items_id), add constraint schiffsbauplan_fk_forschungen foreign key (items_id) references items (id);


update items set schiffsbauplan_schiffstyp_id = substring(effect, LENGTH("draft-ship:")+1, LOCATE("&", effect)-LENGTH("draft-ship:")-1) where typ='Schiffsbauplan';
update items set effect=substring(effect, LOCATE("&", effect)+1) where typ='Schiffsbauplan';
update items set schiffsbauplan_rasse_id = substring(effect, 1, LOCATE('&',effect)-1) where typ='Schiffsbauplan';
update items set effect=substring(effect, LOCATE("&", effect)+1) where typ='Schiffsbauplan';
update items set flagschiff = CASE substring(effect, 1, LOCATE('&',effect)-1) WHEN 'true' THEN TRUE ELSE FALSE END where typ='Schiffsbauplan';
update items set effect=substring(effect, LOCATE("&", effect)+1) where typ='Schiffsbauplan';
update items set crew = substring(effect, 1, LOCATE('&',effect)-1) where typ='Schiffsbauplan';
update items set effect=substring(effect, LOCATE("&", effect)+1) where typ='Schiffsbauplan';
update items set energiekosten = substring(effect, 1, LOCATE('&',effect)-1) where typ='Schiffsbauplan';
update items set effect=substring(effect, LOCATE("&", effect)+1) where typ='Schiffsbauplan';
update items set dauer = substring(effect, 1, LOCATE('&',effect)-1) where typ='Schiffsbauplan';
update items set effect=substring(effect, LOCATE("&", effect)+1) where typ='Schiffsbauplan';
update items set werftSlots = substring(effect, 1, LOCATE('&',effect)-1) where typ='Schiffsbauplan';
update items set effect=substring(effect, LOCATE("&", effect)+1) where typ='Schiffsbauplan';
update items set baukosten = substring(effect, 1, LOCATE('&',effect)-1) where typ='Schiffsbauplan';
update items set effect=substring(effect, LOCATE("&", effect)+1) where typ='Schiffsbauplan';
update items set effect='' where effect=',' and typ='Schiffsbauplan';
insert into schiffsbauplan_forschungen SELECT id,effect from items where typ='Schiffsbauplan' and effect!='';
update items set allianzEffekt = false where typ='Schiffsbauplan';